%bcond_without tests
%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/jazzy/.*$
%global __requires_exclude_from ^/opt/ros/jazzy/.*$

%global __cmake_in_source_build 1

Name:           ros-jazzy-plotjuggler
Version:        3.14.2
Release:        1%{?dist}%{?release_suffix}
Summary:        ROS plotjuggler package

License:        MPL-2.0
URL:            https://github.com/facontidavide/PlotJuggler
Source0:        %{name}-%{version}.tar.gz

Requires:       binutils-devel
Requires:       boost-devel
Requires:       boost-python%{python3_pkgversion}-devel
Requires:       compat-lua-devel
Requires:       cppzmq-devel
Requires:       fmt-devel
Requires:       json-devel
Requires:       libzstd-devel
Requires:       lz4-devel
Requires:       protobuf-compiler
Requires:       protobuf-devel
Requires:       qt5-qtbase-devel
Requires:       qt5-qtsvg-devel
Requires:       qt5-qtwebsockets-devel
Requires:       qt5-qtx11extras-devel
Requires:       ros-jazzy-ament-index-cpp
Requires:       ros-jazzy-data-tamer-cpp
Requires:       ros-jazzy-rclcpp
Requires:       ros-jazzy-ros-workspace
BuildRequires:  binutils-devel
BuildRequires:  boost-devel
BuildRequires:  boost-python%{python3_pkgversion}-devel
BuildRequires:  compat-lua-devel
BuildRequires:  cppzmq-devel
BuildRequires:  fmt-devel
BuildRequires:  json-devel
BuildRequires:  libzstd-devel
BuildRequires:  lz4-devel
BuildRequires:  protobuf-compiler
BuildRequires:  protobuf-devel
BuildRequires:  qt5-qtbase-devel
BuildRequires:  qt5-qtsvg-devel
BuildRequires:  qt5-qtwebsockets-devel
BuildRequires:  qt5-qtx11extras-devel
BuildRequires:  ros-jazzy-ament-cmake
BuildRequires:  ros-jazzy-ament-index-cpp
BuildRequires:  ros-jazzy-data-tamer-cpp
BuildRequires:  ros-jazzy-rclcpp
BuildRequires:  ros-jazzy-ros-workspace
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}

%description
PlotJuggler: juggle with data

%prep
%autosetup -p1

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jazzy/setup.sh" ]; then . "/opt/ros/jazzy/setup.sh"; fi
mkdir -p .obj-%{_target_platform} && cd .obj-%{_target_platform}
%cmake3 \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_PREFIX="/opt/ros/jazzy" \
    -DAMENT_PREFIX_PATH="/opt/ros/jazzy" \
    -DCMAKE_PREFIX_PATH="/opt/ros/jazzy" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
%if !0%{?with_tests}
    -DBUILD_TESTING=OFF \
%endif
    ..

%make_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jazzy/setup.sh" ]; then . "/opt/ros/jazzy/setup.sh"; fi
%make_install -C .obj-%{_target_platform}

%if 0%{?with_tests}
%check
# Look for a Makefile target with a name indicating that it runs tests
TEST_TARGET=$(%__make -qp -C .obj-%{_target_platform} | sed "s/^\(test\|check\):.*/\\1/;t f;d;:f;q0")
if [ -n "$TEST_TARGET" ]; then
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jazzy/setup.sh" ]; then . "/opt/ros/jazzy/setup.sh"; fi
CTEST_OUTPUT_ON_FAILURE=1 \
    %make_build -C .obj-%{_target_platform} $TEST_TARGET || echo "RPM TESTS FAILED"
else echo "RPM TESTS SKIPPED"; fi
%endif

%files
/opt/ros/jazzy

%changelog
* Sat Dec 06 2025 Davide Faconti <davide.faconti@gmail.com> - 3.14.2-1
- Autogenerated by Bloom

* Tue Nov 25 2025 Davide Faconti <davide.faconti@gmail.com> - 3.14.1-1
- Autogenerated by Bloom

* Sat Nov 22 2025 Davide Faconti <davide.faconti@gmail.com> - 3.14.0-1
- Autogenerated by Bloom

* Tue Oct 07 2025 Davide Faconti <davide.faconti@gmail.com> - 3.13.2-1
- Autogenerated by Bloom

* Wed Apr 30 2025 Davide Faconti <davide.faconti@gmail.com> - 3.10.1-1
- Autogenerated by Bloom

* Wed Apr 30 2025 Davide Faconti <davide.faconti@gmail.com> - 3.10.0-1
- Autogenerated by Bloom

* Wed May 08 2024 Davide Faconti <davide.faconti@gmail.com> - 3.9.2-1
- Autogenerated by Bloom

* Sun Apr 28 2024 Davide Faconti <davide.faconti@gmail.com> - 3.9.1-1
- Autogenerated by Bloom

* Fri Apr 19 2024 Davide Faconti <davide.faconti@gmail.com> - 3.9.0-3
- Autogenerated by Bloom

* Wed Mar 06 2024 Davide Faconti <davide.faconti@gmail.com> - 3.9.0-2
- Autogenerated by Bloom

